Python tutorial website:
<br>
https://www.learnpython.org/
<br>
https://www.datacamp.com/home

# The Python Programming Language: Functions

In [1]:
x = 1
y = 2
x + y

3

In [2]:
x

1

<br>
`add_numbers` is a function that takes two numbers and adds them together.

In [3]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

<br>
`add_numbers` updated to take an optional 3rd parameter. Using `print` allows printing of multiple expressions within a single cell.

In [4]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1, 2))
print(add_numbers(1, 2, 3))

3
6


<br>
`add_numbers` updated to take an optional flag parameter.

In [5]:
def add_numbers(x, y, z=None, flag=False):
    if (flag):
        print('Flag is true!')
    if (z==None):
        return x + y
    else:
        return x + y + z
    
print(add_numbers(1, 2, flag=True))

Flag is true!
3


<br>
Assign function `add_numbers` to variable `a`.

In [6]:
def add_numbers(x,y):
    return x+y

a = add_numbers
a(1,2)


3

<br>
# The Python Programming Language: Types and Sequences

<br>
Use `type` to return the object's type.

In [7]:
type('This is a string')

str

In [8]:
type(None)

NoneType

In [9]:
type(1)

int

In [10]:
type(1.0)

float

In [11]:
type(add_numbers)

function

<br>
Tuples are an immutable data structure (cannot be altered).

In [12]:
x = (1, 'a', 2, 'b')
type(x)

tuple

<br>
Lists are a mutable data structure.

In [13]:
x = [1, 'a', 2, 'b']
type(x)

list

<br>
Use `append` to append an object to a list.

In [14]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 3.3]


<br>
This is an example of how to loop through each item in the list.

In [15]:
for item in x:
    print(item)

1
a
2
b
3.3


<br>
Or using the indexing operator:

In [16]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

1
a
2
b
3.3


<br>
Use `+` to concatenate lists.

In [17]:
[1,2] + [3,4]

[1, 2, 3, 4]

<br>
Use `*` to repeat lists.

In [18]:
[1]*3

[1, 1, 1]

<br>
Use the `in` operator to check if something is inside a list.

In [19]:
1 in [1, 2, 3]

True

# Exercise 1

Write a Python function to multiply all the numbers in a list.

In [20]:
def multiply(numbers):  
    x = 1
    for i in numbers:
        x *= i
    return x

print(multiply((8, 2, 3, -1, 7)))

-336


<br>
# The Python Programming Language: Strings

<br>
Now let's look at strings. Use bracket notation to slice a string.

In [21]:
x = 'This is a string'
print(x[0]) #first character
print(x[0:1]) #first character, but we have explicitly set the end character
print(x[0:2]) #first two characters


T
T
Th


<br>
This will return the last element of the string.

In [22]:
x[-1]

'g'

<br>
This will return the slice starting from the 4th element from the end and stopping before the 2nd element from the end.

In [23]:
x[-4:-2]

'ri'

<br>
This is a slice from the beginning of the string and stopping before the 3rd element.

In [24]:
x[:3]

'Thi'

<br>
And this is a slice starting from the 3rd element of the string and going all the way to the end.

In [25]:
x[3:]

's is a string'

In [26]:
firstname = 'Lionel'
lastname = 'Messi'

print(firstname + ' ' + lastname)
print(firstname*3)
print('Lion' in firstname)


Lionel Messi
LionelLionelLionel
True


<br>
`split` returns a list of all the words in a string, or a list split on a specific character.

In [27]:
firstname = 'Harry Edward Kane'.split(' ')[0] # [0] selects the first element of the list
lastname = 'Harry Edward Kane'.split(' ')[-1] # [-1] selects the last element of the list
print(firstname)
print(lastname)

Harry
Kane


<br>
Make sure you convert objects to strings before concatenating.

In [28]:
'Kane' + 2

TypeError: must be str, not int

In [29]:
'Kane' + str(2)

'Kane2'

<br>
Dictionaries associate keys with values.

In [30]:
x = {'Harry Kane': 5, 'Cristiano Ronaldo': 4}
x['Cristiano Ronaldo'] # Retrieve a value by using the indexing operator


4

In [32]:
x['Thomas Müller'] = None
x['Thomas Müller']

<br>
Iterate over all of the keys:

In [33]:
for player in x:
    print(x[player])

5
4
None


<br>
Iterate over all of the values:

In [34]:
for NGoal in x.values():
    print(NGoal)

5
4
None


<br>
Iterate over all of the items in the list:

In [35]:
for player, NGoal in x.items():
    print(player)
    print(NGoal)

Harry Kane
5
Cristiano Ronaldo
4
Thomas Müller
None


<br>
You can unpack a sequence into different variables:

In [36]:
x = ('Cristiano Ronaldo', 'Portugal', 4)
player, country, NGoal = x

In [37]:
player

'Cristiano Ronaldo'

In [38]:
country

'Portugal'

In [39]:
NGoal

4

<br>
Make sure the number of values you are unpacking matches the number of variables being assigned.

In [40]:
x = ('Cristiano Ronaldo', 'Portugal', 4, 'FW')
player, country, NGoal = x

ValueError: too many values to unpack (expected 3)

<br>
Python has a built in method for convenient string formatting.

In [41]:
shots_record = {
'NGoal': 6,
'NShot': 12,
'country': 'England'}

shots_statement = '{} has {} goals in {} shots. Accuracy is {} %.'

print(shots_statement.format(shots_record['country'],
                             shots_record['NGoal'],
                             shots_record['NShot'],
                             shots_record['NGoal']/shots_record['NShot']*100))


England has 6 goals in 12 shots. Accuracy is 50.0 %.


In [42]:
type(shots_record)

dict

# Exercise 2

Write a Python program to combine values in python list of dictionaries.

In [43]:
from collections import Counter
item_list = [{'item': 'item1', 'amount': 400}, {'item': 'item2', 'amount': 300}, {'item': 'item1', 'amount': 750}]
result = Counter()
for iitem in item_list:
    result[iitem['item']] += iitem['amount']
    
print(result) 


Counter({'item1': 1150, 'item2': 300})


# World Cup 2018

https://www.fifa.com/worldcup/ <br>
https://sports.now.com/home/worldcup2018/home

Fancy Prediction <br>
* Prediction = Germany - https://www.kdnuggets.com/2018/06/football-world-cup-predictions.html <br>
* Prediction = Germany - http://www.businessinsider.com/who-will-win-the-world-cup-2018-2018-5 from UBS <br>
* 2018-06-11 - World Cup 2018: Goldman Sachs predicts Brazil will get revenge against Germany <br>
https://www.cnbc.com/2018/06/11/goldman-sachs-predicts-brazil-will-get-world-cup-revenge-against-germany.html <br>
* 2018-07-04 - FIFA World Cup 2018: Goldman Sachs predicts new World Cup winner <br>
https://www.moneycontrol.com/news/trends/sports-trends/fifa-world-cup-2018-goldman-sachs-predicts-new-world-cup-winner-2666911.html <br>
* 2018-07-09 - Goldman Sachs once again changes its World Cup predictions — and is now forecasting a Belgium-England final <br>
http://www.businessinsider.com/world-cup-predictions-goldman-sachs-ai-model-belgium-england-final <br>


Dataset in Kaggle <br>
https://www.kaggle.com/agostontorok/soccer-world-cup-2018-winner/data

<br>
# Reading and Writing CSV files

<br>
Let's import our datafile results_sample2018.csv, which contains 368 international matches results in 2018.

* date - date of the match
* home_team - the name of the home team
* away_team - the name of the away team
* home_score - full-time home team score including extra time, not including penalty-shootouts
* away_score - full-time away team score including extra time, not including penalty-shootouts
* tournament - the name of the tournament
* city - the name of the city/town/administrative unit where the match was played
* country - the name of the country where the match was played
* neutral - TRUE/FALSE column indicating whether the match was played at a neutral venue

In [44]:
import csv

with open('results_sample2018.csv') as csvfile:
    d_results = list(csv.DictReader(csvfile))
    
d_results[:3] # The first three dictionaries in our list.

[OrderedDict([('date', '2018-01-02'),
              ('home_team', 'Iraq'),
              ('away_team', 'United Arab Emirates'),
              ('home_score', '0'),
              ('away_score', '0'),
              ('tournament', 'Friendly'),
              ('city', 'Kuwait City'),
              ('country', 'Kuwait'),
              ('neutral', 'TRUE')]),
 OrderedDict([('date', '2018-01-02'),
              ('home_team', 'Oman'),
              ('away_team', 'Bahrain'),
              ('home_score', '1'),
              ('away_score', '0'),
              ('tournament', 'Friendly'),
              ('city', 'Kuwait City'),
              ('country', 'Kuwait'),
              ('neutral', 'TRUE')]),
 OrderedDict([('date', '2018-01-05'),
              ('home_team', 'Oman'),
              ('away_team', 'United Arab Emirates'),
              ('home_score', '0'),
              ('away_score', '0'),
              ('tournament', 'Friendly'),
              ('city', 'Kuwait City'),
              ('country', 'K

<br>
`csv.Dictreader` has read in each row of our csv file as a dictionary. `len` shows that our list is comprised of 368 dictionaries.

In [45]:
len(d_results)

368

<br>
`keys` gives us the column names of our csv.

In [46]:
d_results[0].keys()

odict_keys(['date', 'home_team', 'away_team', 'home_score', 'away_score', 'tournament', 'city', 'country', 'neutral'])

<br>
This is how to find the average home_score across all home teams. All values in the dictionaries are strings, so we need to convert to float.

In [47]:
sum(float(d['home_score']) for d in d_results) / len(d_results)

1.516304347826087

<br>
Similarly this is how to find the average away_score across all away teams.

In [48]:
sum(float(d['away_score']) for d in d_results) / len(d_results)

1.0815217391304348

<br>
Use `set` to return the unique values for the tournaments played in our dataset have.

In [49]:
tournaments = set(d['tournament'] for d in d_results)
tournaments

{'AFC Asian Cup qualification',
 'Baltic Cup',
 'COSAFA Cup',
 'ConIFA World Football Cup',
 'FIFA World Cup',
 'Friendly'}

<br>
Here's a more complex example where we are grouping the matches by tournaments, and finding the average scores for each tournament.

In [50]:
ScoresByTour = []

for tour in tournaments: # iterate over all the tournaments
    sumscore = 0
    tourmatchcount = 0
    for d in d_results: # iterate over all dictionaries
        if d['tournament'] == tour: # if the tournament matches,
            sumscore += float(d['home_score']) + float(d['away_score']) # add both home and away scores
            tourmatchcount += 1 # increment the count
    ScoresByTour.append((tour, sumscore / tourmatchcount)) # append the tuple ('tour', 'avg scores')

ScoresByTour.sort(key=lambda x: x[0])
ScoresByTour

[('AFC Asian Cup qualification', 3.0),
 ('Baltic Cup', 1.5),
 ('COSAFA Cup', 1.9),
 ('ConIFA World Football Cup', 3.888888888888889),
 ('FIFA World Cup', 2.625),
 ('Friendly', 2.403225806451613)]

<br>
# The Python Programming Language: Dates and Times

In [51]:
import datetime as dt
import time as tm

<br>
`time` returns the current time in seconds since the Epoch. (January 1st, 1970)

In [52]:
tm.time()

1531816787.7729483

<br>
Convert the timestamp to datetime.

In [53]:
dtnow = dt.datetime.fromtimestamp(tm.time())
print(dt.datetime.now())
dtnow

2018-07-17 16:39:50.458568


datetime.datetime(2018, 7, 17, 16, 39, 50, 458569)

<br>
Handy datetime attributes:

In [54]:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc.from a datetime

(2018, 7, 17, 16, 39, 50)

<br>
`timedelta` is a duration expressing the difference between two dates.

In [55]:
delta = dt.timedelta(days = 100) # create a timedelta of 100 days
delta

datetime.timedelta(100)

<br>
`date.today` returns the current local date.

In [56]:
today = dt.date.today()

In [57]:
today - delta # the date 100 days ago

datetime.date(2018, 4, 8)

In [58]:
today > today-delta # compare dates

True

# Exercise 3

Write a Python program to subtract five days from current date.

In [59]:
from datetime import date, timedelta
dt = date.today() - timedelta(5)
print(dt)

2018-07-12


# Competition, For training your data science skills
<br>
http://www.kaggle.com

***

<br>
# Python 102 (Go through the following if we have time)

***

# The Python Programming Language: Objects and map()

<br>
An example of a class in python:

In [60]:
class Manager:
    Tournament = 'World Cup 2018' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_country(self, new_country):
        self.country = new_country

In [61]:
manager = Manager()
manager.set_name('Joachim Löw')
manager.set_country('Germany')
print('Manager of {} International Team in {} is {}'.format(manager.country, manager.Tournament, manager.name))

Manager of Germany International Team in World Cup 2018 is Joachim Löw


In [62]:
type(manager)

__main__.Manager

<br>
Here's an example of mapping the `min` function between two lists.

In [63]:
store1 = [10.00, 11.00, 12.34, 2.34]
store2 = [9.00, 11.10, 12.34, 2.01]
cheapest = map(min, store1, store2)
cheapest

<br>
Now let's iterate through the map object to see the values.

In [64]:
for item in cheapest:
    print(item)

9.0
11.0
12.34
2.01


<br>
# The Python Programming Language: Lambda and List Comprehensions

<br>
Here's an example of lambda that takes in three parameters and adds the first two.

In [65]:
my_function = lambda a, b, c : a + b

In [66]:
my_function(1, 2, 3)

3

<br>
Let's iterate from 0 to 999 and return the even numbers.

In [67]:
my_list = []
for number in range(0, 1000):
    if number % 2 == 0:
        my_list.append(number)
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

<br>
Now the same thing but with list comprehension.

In [68]:
my_list = [number for number in range(0,1000) if number % 2 == 0]
my_list

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

<br>
# The Python Programming Language: Numerical Python (NumPy)

In [69]:
import numpy as np

<br>
## Creating Arrays

Create a list and convert it to a numpy array

In [70]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

<br>
Or just pass in a list directly

In [71]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

<br>
Pass in a list of lists to create a multidimensional array.

In [72]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

<br>
Use the shape method to find the dimensions of the array. (rows, columns)

In [73]:
m.shape

(2, 3)

<br>
`arange` returns evenly spaced values within a given interval.

In [74]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

<br>
`reshape` returns an array with the same data with a new shape.

In [75]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

<br>
`linspace` returns evenly spaced numbers over a specified interval.

In [76]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

<br>
`resize` changes the shape and size of array in-place.

In [77]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

<br>
`ones` returns a new array of given shape and type, filled with ones.

In [78]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [79]:
np.ones((3,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

<br>
`zeros` returns a new array of given shape and type, filled with zeros.

In [80]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

<br>
`eye` returns a 2-D array with ones on the diagonal and zeros elsewhere.

In [81]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<br>
`diag` extracts a diagonal or constructs a diagonal array.

In [82]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

<br>
Create an array using repeating list (or see `np.tile`)

In [83]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

<br>
Repeat elements of an array using `repeat`.

In [84]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

<br>
#### Combining Arrays

In [85]:
p = np.ones([2, 3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

<br>
Use `vstack` to stack arrays in sequence vertically (row wise).

In [86]:
np.vstack([p, 2*p])

array([[1, 1, 1],
       [1, 1, 1],
       [2, 2, 2],
       [2, 2, 2]])

<br>
Use `hstack` to stack arrays in sequence horizontally (column wise).

In [87]:
np.hstack([p, 2*p])

array([[1, 1, 1, 2, 2, 2],
       [1, 1, 1, 2, 2, 2]])

<br>
## Operations

Use `+`, `-`, `*`, `/` and `**` to perform element wise addition, subtraction, multiplication, division and power.

In [88]:
print(x + y) # elementwise addition     [1 2 3] + [4 5 6] = [5  7  9]
print(x - y) # elementwise subtraction  [1 2 3] - [4 5 6] = [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [89]:
print(x * y) # elementwise multiplication  [1 2 3] * [4 5 6] = [4  10  18]
print(x / y) # elementwise divison         [1 2 3] / [4 5 6] = [0.25  0.4  0.5]

[ 4 10 18]
[0.25 0.4  0.5 ]


In [90]:
print(x**2) # elementwise power  [1 2 3] ^2 =  [1 4 9]

[1 4 9]


<br>
**Dot Product:**  

$ \begin{bmatrix}x_1 \ x_2 \ x_3\end{bmatrix}
\cdot
\begin{bmatrix}y_1 \\ y_2 \\ y_3\end{bmatrix}
= x_1 y_1 + x_2 y_2 + x_3 y_3$

In [91]:
x.dot(y) # dot product  1*4 + 2*5 + 3*6

32

In [92]:
z = np.array([y, y**2])
print(len(z)) # number of rows of array

2


<br>
Let's look at transposing arrays. Transposing permutes the dimensions of the array.

In [93]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

<br>
The shape of array `z` is `(2,3)` before transposing.

In [94]:
z.shape

(2, 3)

<br>
Use `.T` to get the transpose.

In [95]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

<br>
The number of rows has swapped with the number of columns.

In [96]:
z.T.shape

(3, 2)

<br>
Use `.dtype` to see the data type of the elements in the array.

In [97]:
z.dtype

dtype('int32')

<br>
Use `.astype` to cast to a specific type.

In [98]:
z = z.astype('f')
z.dtype

dtype('float32')

<br>
## Math Functions

Numpy has many built in math functions that can be performed on arrays.

In [99]:
a = np.array([-4, -2, 1, 3, 5])

In [100]:
a.sum()

3

In [101]:
a.max()

5

In [102]:
a.min()

-4

In [103]:
a.mean()

0.6

In [104]:
a.std()

3.2619012860600183

<br>
`argmax` and `argmin` return the index of the maximum and minimum values in the array.

In [105]:
a.argmax()

4

In [106]:
a.argmin()

0

<br>
## Indexing / Slicing

In [107]:
s = np.arange(13)**2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144],
      dtype=int32)

<br>
Use bracket notation to get the value at a specific index. Remember that indexing starts at 0.

In [108]:
s[0], s[4], s[-1]

(0, 16, 144)

<br>
Use `:` to indicate a range. `array[start:stop]`


Leaving `start` or `stop` empty will default to the beginning/end of the array.

In [109]:
s[1:5]

array([ 1,  4,  9, 16], dtype=int32)

<br>
Use negatives to count from the back.

In [110]:
s[-4:]

array([ 81, 100, 121, 144], dtype=int32)

<br>
A second `:` can be used to indicate step-size. `array[start:stop:stepsize]`

Here we are starting 5th element from the end, and counting backwards by 2 until the beginning of the array is reached.

In [111]:
s[-5::-2]

array([64, 36, 16,  4,  0], dtype=int32)

<br>
Let's look at a multidimensional array.

In [112]:
r = np.arange(36)
r.resize((6, 6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

<br>
Use bracket notation to slice: `array[row, column]`

In [113]:
r[2, 2]

14

<br>
And use : to select a range of rows or columns

In [114]:
r[3, 3:6]

array([21, 22, 23])

<br>
Here we are selecting all the rows up to (and not including) row 2, and all the columns up to (and not including) the last column.

In [115]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

<br>
This is a slice of the last row, and only every other element.

In [116]:
r[-1, ::2]

array([30, 32, 34])

<br>
We can also perform conditional indexing. Here we are selecting values from the array that are greater than 30. (Also see `np.where`)

In [117]:
r[r > 30]

array([31, 32, 33, 34, 35])

<br>
Here we are assigning all values in the array that are greater than 30 to the value of 30.

In [118]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
## Copying Data

Be careful with copying and modifying arrays in NumPy!


`r2` is a slice of `r`

In [119]:
r2 = r[:3,:3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

<br>
Set this slice's values to zero ([:] selects the entire array)

In [120]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

<br>
`r` has also been changed!

In [121]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
To avoid this, use `r.copy` to create a copy that will not affect the original array

In [122]:
r_copy = r.copy()
r_copy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

<br>
Now when r_copy is modified, r will not be changed.

In [123]:
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


<br>
### Iterating Over Arrays

Let's create a new 4 by 3 array of random numbers 0-9.

In [124]:
test = np.random.randint(0, 10, (4,3))
test

array([[7, 1, 4],
       [8, 9, 1],
       [1, 5, 6],
       [2, 1, 9]])

<br>
Iterate by row:

In [125]:
for row in test:
    print(row)

[7 1 4]
[8 9 1]
[1 5 6]
[2 1 9]


<br>
Iterate by index:

In [126]:
for i in range(len(test)):
    print(test[i])

[7 1 4]
[8 9 1]
[1 5 6]
[2 1 9]


<br>
Iterate by row and index:

In [127]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [7 1 4]
row 1 is [8 9 1]
row 2 is [1 5 6]
row 3 is [2 1 9]


<br>
Use `zip` to iterate over multiple iterables.

In [128]:
test2 = test**2
test2

array([[49,  1, 16],
       [64, 81,  1],
       [ 1, 25, 36],
       [ 4,  1, 81]], dtype=int32)

In [129]:
for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)

[7 1 4] + [49  1 16] = [56  2 20]
[8 9 1] + [64 81  1] = [72 90  2]
[1 5 6] + [ 1 25 36] = [ 2 30 42]
[2 1 9] + [ 4  1 81] = [ 6  2 90]


In [130]:
x = np.arange(36)
x.resize((6,6))
print(x)
print(x[(2,4),(2,4)])

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[14 28]
